baseurl = "https://bewegungsappar.at/"
languageCode = "en"
title = "bewegungsappar.at"
copyright = "meet us at 36c3 at the hacKNology assembly. Or contact phail for further Information: phail@bewegungsappar.at"
paginate = 3

theme = "minimage"

[params]
  description = "Dry it at 36c3"
  author = "hacKNology e.V."
  logo = 'img/flotte.jpg'

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "software"
    url = "/post/software/"

[[menu.global]]
    name = "mechanical"
    url = "/post/mechanical/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"

